### ISSUE TITLE
-Dmaximise argument causes NullPoint exception with recent versions of chrome

### ISSUE THREAD

**Issue by david-apples** [Frameworkium/frameworkium-core#102]
If the maximise option is used with recent versions of chrome an exception 'Failed to configure Browser' is reported with a NullPointException.

Current workaround is to manually set browser size in tests:

    getDriver().manage().window().setSize(new Dimension(1920, 1200));

**Comment by ham1** [comment]
Is this a Frameworkium issue? Or does it lie in Chrome, ChromeDriver or grid/Docker?

**Comment by ham1** [comment]
Any update on this issue?

**Comment by ham1** [comment]
Closing, please re-open if still an issue.
