### ISSUE TITLE
[Appium Remote] 400 The plain HTTP request was sent to HTTPS port

### ISSUE THREAD

**Issue by asharma88** [Frameworkium/frameworkium-core#108]
Hello,

I seem to be getting the following error when I try and create a Custom Browser Implementation.

[ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 4.05 s <<< FAILURE! - in TestSuite
[ERROR] instantiateDriverObject(com.what3words.tests.MapTest)  Time elapsed: 3.744 s  <<< FAILURE!
org.openqa.selenium.WebDriverException: 
Unable to parse remote response: <html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx/1.12.1</center>
</body>
</html>

I tried to look online for solutions to this problem without luck. Please could you help me out explaining when I create a simple class with a main object and I instantiate my driver etc it has no issues with the ssl problem??

CustomDriverImpl source -> https://pastebin.com/JTJsTB4r

Thanks Arjun

**Comment by ham1** [comment]
Line 37, try changing https to http

**Comment by asharma88** [comment]
I have tried this Graham, unfortunately the endpoint from the service I'm using is HTTPS based.. do you know / think of any reason why frameworkium could mess with the appium connectivity?


https://github.com/kobiton/samples/blob/master/java/java_testng_junit/src/main/java/kobiton/com/testng/iOSWebTest.java

Configs -> https://github.com/kobiton/samples/blob/master/java/java_testng_junit/src/main/java/kobiton/com/configs/Configs.java

Br,
Arjun Sharma

**Comment by asharma88** [comment]
So turns out, I just need to use RemoteWebDriver the same as used in Saucelabs :)
