### ISSUE TITLE
Modify the default wait time for @Visible annotations

### ISSUE THREAD

**Issue by davecpayne** [Frameworkium/frameworkium-core#148]
Per my question on StackOverflow: https://stackoverflow.com/questions/59052480/is-there-any-way-to-increase-the-default-wait-in-frameworkium-for-visible-anno

I presume there's no way to increase the default timeout while waiting for an element to be `@Visible`, since this seems to be hard-coded in `UITestLifecycle`. Is that correct? Is there any workaround besides not using that annotation and doing it the 'standard' Selenium way (in which case I'm not sure the benefits of Frameworkium would outweigh the downsides).

**Comment by ham1** [comment]
I've just also answered the question on SO.

The `@Visible` uses the wait defined on the `Page` object.

Therefore, if you'd like to change it you have to change the way the page is constructed. There are two options for this:

1. If you are using the `PageFactory you can use PageFactory.newInstance(MyPage.class, Duration.of(20, SECONDS))` or
2. `new MyPage().get(Duration.ofSeconds(20))`

or, if this is popular we would consider customising the default (PRs welcome).

**Comment by davecpayne** [comment]
Ah, brilliant, thank you, I'll give that a try. I think it's only the one page, so I'll look at those options.
