### ISSUE TITLE
How to find if a web table text exists under a specific column, if the column is not a header?

### ISSUE THREAD

**Issue by sridharaiyer** [Frameworkium/frameworkium-core#156]

**Comment by Mjl33** [comment]
This is a question related to CSS and Selenium specifically. 
I would like to direct you to Selenium interest groups such as [https://groups.google.com/g/selenium-users](https://groups.google.com/g/selenium-users) for detailed answers.

That said, I can offer you general steps towards a solution for your problem without having any further context to your problem.
Try to locate them via CSS locators and use '.isDisplayed()' method from Selenium to check for existence.

I am closing this as this is a question for Selenium
