### ISSUE TITLE
@Name annotation throw default value exception

### ISSUE THREAD

**Issue by praveenraj123** [Frameworkium/frameworkium-core#334]
Hi team 

Recently I have updated frameworkium 4.1.0.2 vertion once I update my pom file it's throw exception all my page object class than I have to import web elements for respective package and  my code is unable to run because of issues @name anotion throw some default value missed exception and chrome options exception kindly help us ASAP

**Comment by Mjl33** [comment]
HtmlElements has been move to internal library `com.frameworkium.core.htmlelements`
In effect @Name has been deprecated and no longer in use

If you would like to continue to use the older HtmlElements, you will have to import dependencies from
`https://mvnrepository.com/artifact/io.qameta.htmlelements/htmlelements`

Note that this library is no longer maintained, and we recommend that you use our internal version
