### ISSUE TITLE
Click on non-visible links by default

### ISSUE THREAD

**Issue by sridharaiyer** [Frameworkium/frameworkium-core#356]
**Description**
I am automating a web app where there are a lot of links that are visible when you scroll down. I want frameworkium to click on these links without having to use the forceVisible and executeJS block every time for this.

**To Reproduce**
1. Launch a web app where there a lot of links at the bottom only visible when you scroll down
2. Use <link element>.click()
3. See error: Link not clickable

**Workaround**
You need to keep using this block to make the element and then click or perform any action on it - 
 ```
        WebElement somelink = driver.findElement(By.linkText("some link"));
        forceVisible(somelink);
        executeJS("arguments[0].scrollIntoView(true);", somelink);
        somelink.click();
```

**Expected Behaviour**
Should click on the link (or do any other action on an element) wherever it is located in the app (as long as it is enabled)

**Screenshots**

**Versions (please complete the following information):**
 - Frameworkium-core version: 3.0.0
 - OS: Win/Mac
 - Browser: Chrome
 - Version: 100.0.4896.60

**Comment by Mjl33** [comment]
It sounds like you need to wait for the links to be clickable.
This is a Selenium related question, please post your question here https://groups.google.com/g/selenium-users

Note, forceVisible is only used when elements are permanently invisible
