### ISSUE TITLE
How to extend the BasePage

### ISSUE THREAD

**Issue by sridharaiyer** [Frameworkium/frameworkium-core#357]
**Describe the Issue**
I have a use case where I need to have custom waits for my application, scroll into view for many elements and click on them. So I need a way to extend the BasePage class myself where I can add my custom functions that can be used by all my Page Object Classes.

**To Reproduce**
 I tried this:

`class MyBasePage extends BasePage<MyBasePage>(){}`

But when I use my Page Object class, let's say LoginPage to extend this class as - 

`class LoginPage extends MyBasePage`
or
`class LoginPage extends MyBasePage<LoginPage>`

I am running into compilation errors.

Kindly let me know the most suitable way to extend the BasePage so that I can add my additional logic.

**Comment by Mjl33** [comment]
class BasePageExtended<T extends BasePage<T>> extends BasePage<T>
