### ISSUE TITLE
Aysnchronous script timeout

### ISSUE THREAD

**Issue by Mjl33** [Frameworkium/frameworkium-core#37]
There is a bug which often crops on angularJS pages, which reads 

**TimeoutException: asynchronous script timeout: result was not received in 10 seconds** 

Updating the ngwebdriver dependency to 0.9.7 seems fix this

```
<dependency>
  <groupId>com.paulhammant</groupId>
  <artifactId>ngwebdriver</artifactId>
  <version>0.9.7</version>
  <scope>test</scope>
</dependency>
```

**Comment by robertgates55** [comment]
2.0.7 includes the fix for this

**Comment by srishtis9** [comment]
Hi , I am getting the error :
 TimeoutException: asynchronous script timeout: result was not received in 10 seconds

whenever i try to use the methods in another page object class . However if i put all the elements and methods in the same page Object class , the script works perfectly.

I am following the guidelines in the doc  : 

If an action on a page results in moving to a new page, then you can instantiate a new Page Object in one of two ways:

return new NextPagePageObject().get(); or
return PageFactory.newInstance(NextPagePageObject.class);

**Comment by ham1** [comment]
- Which version are you using?
- Could you show your code that is trying to run the async JavaScript?
- Does it always happen or just sometimes?
- If you keep everything in the same page object, which you says works, and just create a new instance of that page object, does the error still occur?

**Comment by srishtis9** [comment]
@ham1 

I am using frameworkium-BDD  version 2.4.2 , which uses frameworkium-core version 2.4.3 .

I am trying to automate an angular page , am not running any async javascript code 

Code Sample :

public class ConsolePage extends BasePage<ConsolePage> {
	
	@Name("Help Icon")
	@Visible
	@FindBy(css = "button[title = 'Help']") 
	private WebElement helpIcon ; 
	
	@Name("Support Center tab")
	@FindBy(xpath = "//span[contains(text() ,'Support Center')]") 
	private WebElement supportCenterTab ;
	
	
	@Name("Create Button")
	@FindBy(xpath = "//button[contains(text() , 'Create BUTTON')]")
	private WebElement createbtn ;
	
	@Step("click on the help icon ")
	public ConsolePage clickHelpIcon() {
		helpIcon.click();
		return this ;
	}
	
	@Step("click on the support center tab to go to the SR page")
	public SrPage goToSrPage() {
		
		supportCenterTab.click();
		return new SrPage().get();
		
	}
	
	@Step("click on create  btn ")
	public void create() throws InterruptedException {
		Thread.sleep(10000);
		btn.click();
		
	}

	}


So when am on the ConsolePage and try to navigate to the SrPage via the method  goToSrPage() , which returns an instance of the SrPage , am not able to perform any action , and get the error : 

TimeoutException: asynchronous script timeout: result was not received in 10 seconds


With everything in one page object , the error does not occur .

 To create the instance of this page  , i use the method  get() :

@Step("Navigate to the google page")
	public static DiscoveryPage open() {
		
		 return new DiscoveryPage().get("https://google.com");
	}

**Comment by noronhaa** [comment]
Hi @srishtis9 

I have created a branch called 'angular' on the frameworkium-bdd project https://github.com/Frameworkium/frameworkium-bdd.git and have created a test navigating across 2 angular webpages and is working on my end. would be good to see if this would work for you also or if you still get the same problem so we can narrow down the problem. Its all configured to run the single angular test so you should just need to run `mvn clean install` adding your with your driver and browser settings and let me know how it runs

Also can you post a full stack trace so we can see where the error is coming from exactly.

Lastly is the webpage taking a long time to load or loading quickly as expected?

Thanks

**Comment by srishtis9** [comment]
@noronhaa  mentioning again , if i put the same set of code in the same page object , everything works fine .

Thanks

**Comment by noronhaa** [comment]
When you have the page objects what does the method look like where you do an action to switch to an actual different webpage. I am guessing you are not instantiating a new PageObject but doing `return this;` ?

Your test is actually failing due to a method we run when a new page loads that will wait for all Angular requests on the page to finish - this is actually a bit of js code that runs under the hood. we also see a  another error:

`org.openqa.selenium.JavascriptException: javascript error: document unloaded while waiting for result
`

My theory at the moment is that we are waiting for angular requests to load before the new page starts to load. the new page loading then interrupts the js method and throws an error. to prove this is the case could you put a sleep in your method like below and tell me if you get the same error

```
public SrPage goToSrPage() {
	
	supportCenterTab.click();
        Thread.sleep(3000);
	return new SrPage().get();
	
}

Thanks

**Comment by srishtis9** [comment]
@noronhaa 

My scenario includes navigation between different web pages , but i have created a single class (Page object ) , which contains WebElements (of all the different web pages) as class data members and the methods , which actually involve action which will navigate to another web page , return either this or void.

I tried your suggested approach , putting explicit wait between the action leading to next web page and the return statement in the page object class , but the script still fails .

Code : 
@Step("Enter the credentials and land to console page") // return the console page 
	public ConsoleTestPage signIn(String username , String password ) throws InterruptedException {
		
		usernameField.sendKeys(username);
		nextBtn.click();
		Thread.sleep(20000);
		
		passwordField.sendKeys(password);
		signinBtn.click();
		Thread.sleep(20000);
		return new ConsoleTestPage().get();
	}

Error message  :
org.openqa.selenium.ScriptTimeoutException: asynchronous script timeout: result was not received in 10 seconds

Note
org.openqa.selenium.JavascriptException: javascript error: document unloaded while waiting for result : didnot appear in the stack trace.

**Comment by ham1** [comment]
Could you post the relevant part of the test run from the `frameworkium.log`?

Thanks
