### ISSUE TITLE
BasePageExtended causing issue with wait

### ISSUE THREAD

**Issue by sridharaiyer** [Frameworkium/frameworkium-core#373]
**Describe the Issue**
This is reopening the issue #357 
I extended the BasePage as `public class BasePageExtended<T extends BasePage> extends BasePage`
And extended this class for my page object class as:
`public class MyPage extends BasePageExtended<MyPage> `

I am unable to use the `wait.until` methods in my page object as the compiler complains saying it is expecting a WebElement but getting an object instead

**To Reproduce**
1. Mentioned in description

**Expected Behaviour**
Should be able to extend the BasePage as BasePageExtended and extend that for my pages without any issue.
<img width="991" alt="Screen Shot 2022-04-18 at 11 07 51 AM" src="https://user-images.githubusercontent.com/5684178/163837267-e1fe8166-4c13-4118-ac91-dae314baac2d.png">
<img width="987" alt="Screen Shot 2022-04-18 at 10 55 30 AM" src="https://user-images.githubusercontent.com/5684178/163837271-a41de5f9-5251-4a01-bb16-da4f7a46d171.png">

**Comment by sridharaiyer** [comment]
Hi
I was able to overcome the Wait issue by instantiating the Wait like this - 
```
public class BasePageExtended<T extends BasePage> extends BasePage {
    protected Wait<WebDriver> wait = new WebDriverWait(driver, 30);
```
But I am still seeing some warnings in terms of "generifying" my code, when my pages extend the `BasePageExtended` class. Screenshots below.


<img width="991" alt="Screen Shot 2022-04-18 at 1 42 21 PM" src="https://user-images.githubusercontent.com/5684178/163858242-c9c9555e-03c8-4aed-9c65-1ee2d0339bc4.png">
<img width="991" alt="Screen Shot 2022-04-18 at 1 41 30 PM" src="https://user-images.githubusercontent.com/5684178/163858245-716171f4-1131-4987-a924-137bbcc34a04.png">

Can you kindly help me get rid of these warnings?

**Comment by Mjl33** [comment]
the correct extension is `BasePageExtended<T extends BasePage<T>> extends BasePage<T>`

**Comment by sridharaiyer** [comment]
Thank you team. The extension is working fine now. Closing this ticket.
