### ISSUE TITLE
jitpack failed to host artifact for latest release version 

### ISSUE THREAD

**Issue by emersonbaillie** [Frameworkium/frameworkium-core#393]
Jitpack build for release version 4.2.1 has failed https://jitpack.io/com/github/Frameworkium/frameworkium-core/4.2.1/build.log

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check (validate) on project frameworkium-core: Execution validate of goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check: java.lang.UnsupportedClassVersionError: com/puppycrawl/tools/checkstyle/api/CheckstyleException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 54.0

The latest release tag cannot be retrieved by maven.

The latest release POM version is also still 4.0.0-BETA2-SNAPSHOT

**Comment by Mjl33** [comment]
This is a jitpack.io build fail, specifically it seems to be incompatibility with 

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check (validate) on project frameworkium-core: Execution validate of goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check: java.lang.UnsupportedClassVersionError: com/puppycrawl/tools/checkstyle/api/CheckstyleException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 54.0`

**Comment by Mjl33** [comment]
Fixed by forcing jitpack to build with JDK11
I have now release 4.2.1 - marked as pre-release

@emersonbaillie If you could try pulling v4.2.1 again and report back

**Comment by emersonbaillie** [comment]
Hi @Mjl33, 
Using 4.2.1 and the maven project is building fine. Tests running fine with Chrome v102 and Frameworkium v4.2.1

Thanks
