### ISSUE TITLE
Allow BasePage to have a keyword that handles generic return page as a parameter

### ISSUE THREAD

**Issue by Mjl33** [Frameworkium/frameworkium-core#42]
## Issue

An interaction on an element would result in navigation to different pages depending on the input
Example:
- On HomePage, setting a valid input to a TextBox and clicking Submit Button would navigate me to SuccessPage
- On HomePage, setting a invalid input to a TextBox and clicking Submit Button would navigate me to FailPage
## Current Implementations

Currently, developers would define multiple methods

``` java
//PO
public SuccessPage clickSubmitButtonAndGotoSuccessPage(){
return PageFactory.newInstance(SuccessPage.class);
}

public FailPage clickSubmitButtonAndGotoFailPage(){
return PageFactory.newInstance(FailPage.class);
}

...

public WhateverPage clickSubmitButtonAndGotoSomeOtherPage(){
return PageFactory.newInstance(WhateverPage.class);
}
```
## Why it stinks

This bloats the PO and quickly becomes unreadable
## Proposed solution

Have a method in BasePage

``` java
withExpectation(? BasePage<?>) 
```

_method name should be change to something better_

This allows me to write,

``` java
//PO
public BasePage clickSubmitButton(){
submitButton.click();
return PageFactory.newInstance(BasePage.class);
}
```

``` java
//Test with valid inputs
homePage.setTextBox("Good Input");
SuccessPage successPage = homePage.clickSubmitButton().withExpectation(SuccessPage.class);

//Test with invalid inputs
homePage.setTextBox("Good Input");
FailPage failPage = homePage.clickSubmitButton().withExpectation(FailPage.class);
```

This would allow me to reuse clickSubmitButton 

**I am just throwing out ideas, I am open to a better implementation**

**Comment by robertgates55** [comment]
Pretty sure this is what you're after? We use it on lots of our login
methods:

https://gist.github.com/ham1/0bf7d1cc59e5e406b53e

It needs to be added to a wiki or an example login method somewhere, if it
is?




R

**Comment by robertgates55** [comment]
Wonder if there's any value in wrappering it as a base page method? What do
you think?

**Comment by Mjl33** [comment]
Yes, this is exactly what I am after.

I am thinking its worth the wrapper

We can : 
- gain readability at test level 
- steer devs away from having to think too much on implementation especially less experience devs
- squeeze that few drops of velocity and probably save ourselves the heartache of code bloat as well

I realize there is a move to slim frameworkium. Would this be too much of a dirt to add in?

**Comment by ham1** [comment]
Sorry I don't quite understand. What would the wrapper in BasePage look like given the required code in the page object is:
```java
public <T extends BasePage<T>> T savePage(Class<T> expectedPageObjectClass) {
    // do something ...
    return PageFactory.newInstance(expectedPageObjectClass);
}
```

**Comment by Mjl33** [comment]
Let's hold this off for now, the devs here got comfy with the generic method very quickly when I showed them.

**Comment by ham1** [comment]
Ok, closing for now, feel free to re-open if required.
