### ISSUE TITLE
Reusing the same browser across multiple tests 

### ISSUE THREAD

**Issue by ronaldoshaky** [Frameworkium/frameworkium-core#66]
Hi this is not really an issue, just an "annoyance"

Is there a way with frameworkium, that I can load the browser once and use the same browser instance for all tests, rather than having each test spin it up and then shutting it down?

**Comment by Mjl33** [comment]
@ronaldoshaky 
The browser tear up and teardown would ensure a pristine state per test
What would be your use case?

**Comment by ham1** [comment]
I would guess speed of execution. However there is an issue whereby Selenium cannot clear the browser's cache, which will be ok most of the time but may cause some unexpected differences if run with a fresh browser each time.

We are currently working to address this issue by adding the option to reuse browsers, #81.
